# Generated by Django 2.2.17 on 2021-04-12 23:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210413_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
